### ISSUE TITLE
pre-extracted embeddings calculation 

### ISSUE THREAD

**Issue by TanmDL** [prov-gigapath/prov-gigapath#1]
Thank you for sharing the code. It is a fantastic work. However, I have a question regarding the slide-level feature from the 'pre-extracted embeddings.' Which tools did you use for calculating the 'pre-extracted embeddings'?

**Comment by HanwenXuTHU** [comment]
Thanks for reaching out! Getting slide-level embeddings incorporate two steps: (1) Use GigaPath's encoder to extract the embeddings for each tile. Each embedding has a dimension of D, suppose we have N tile embeddings, so we should collect a [N, D] tensor. (2) For each tile, we collect its X-Y coordinate on the original whole slide, getting a [N, 2] tensor. Then we pass the tile embeddings and associated coordinates to GigaPath's slide encoder. 

For your reference, we released a demo to show how to run inference with GigaPath's encoder, please check this [script](https://github.com/prov-gigapath/prov-gigapath/blob/main/demo/load_tile_encoder.py).

**Comment by HanwenXuTHU** [comment]
Hi, I just close this issue for now. Feel free to reach out and re-open it if you run into other problems.
