### ISSUE TITLE
cannot find model (vit_giant_patch14_dinov2) when loading tile encoder

### ISSUE THREAD

**Issue by nmduonggg** [prov-gigapath/prov-gigapath#11]
Hi, thanks for sharing such a wonderful project. I am trying to use tile encoder only for feature extraction. However when I follow your instructions, the error occurs in `timm.create_model("timm.create_model("hf_hub:prov-gigapath/prov-gigapath", pretrained=True)"`. It seems like the link directs to "vit_giant_patch14_dinov2" pretrained weight, which I cannot find in timm in Hugging Face.
So can you check again the availability of tile encoder pretrained weights please? It might be removed or missing for some reasons ? Thanks for answering.

**Comment by HanwenXuTHU** [comment]
Thanks for reaching out! The tile encoder is always there. Can you share your timm version the exact code you're using to load the model?

**Comment by WenxiongLiao** [comment]
pip install timm==1.0.3
Maybe you can solve it by updating timm

**Comment by nmduonggg** [comment]
I solved this. Thanks for your help !
