### ISSUE TITLE
How about 256×256-pixel tile images with 10× magnification

### ISSUE THREAD

**Issue by WenxiongLiao** [prov-gigapath/prov-gigapath#13]
The model shown in the paper is for 256×256-pixel tile images with **20× magnification**. Is this model applicable to 256×256-pixel tile images with **10× magnification**? If so, will the performance be degraded?

**Comment by HanwenXuTHU** [comment]
Hi, this is quite an interesting question. We didn't explore 10 x magnification in our paper. I think the performance changes really depend on tasks. For tasks that need to focus on local detailed patterns, it might degrade a bit.
