### ISSUE TITLE
Classification head for downstream tasks different from paper

### ISSUE THREAD

**Issue by yihu-dev** [prov-gigapath/prov-gigapath#14]
Hi, 

In the paper, the contexualized tile embeddings are aggregated by a AMBIL layer:
> We fine-tuned Prov-GigaPath and other baseline models on diverse downstream tasks. For Prov-GigaPath, we froze the tile encoder and only fine-tuned the LongNet slide-level encoder. For each slide, LongNet produces a set of contextualized tile embeddings. These are aggregated using a shallow ABMIL layer to obtain the slide embeddings, which are then used in additional classifiers for downstream prediction tasks. 

But the code in slide_encoder.py and classification_head.py shows that it uses CLS embedding followed by a linear layer.
To repreduce the numbers, I would do replace:
```
        outcomes = []
        for x in x_list:
            if self.global_pool:
                x = x[:, 1:, :].mean(dim=1)  # global average pooling
                outcome = self.norm(x)
            else:
                x = self.norm(x)
                outcome = x[:, 0]
            outcomes.append(outcome)

        return outcomes
```
with simply return x_list of the last layer of LongViT and then add ABMIL and an additional linear layer.
Is it correct?

Thanks.

**Comment by HanwenXuTHU** [comment]
Hi, using the CLS pooling is fine. In our release, we just switch to use the standard CLS pooling as the output features.

**Comment by yihu-dev** [comment]
Thanks for clarification.

**Comment by HanwenXuTHU** [comment]
Closed the issue for now. Feel free to re-open it if you have any further question.
