### ISSUE TITLE
Visualizing Attention Weights

### ISSUE THREAD

**Issue by adas2125** [prov-gigapath/prov-gigapath#17]
Hi, thank you and congratulations on your excellent publication. I was wondering if there were ways to visualize attention weights with this pipeline. I am aware that this uses Dilated Attention and was wondering if you had any suggestions. Thanks for your help.

**Comment by HanwenXuTHU** [comment]
Hi thanks for reaching out! This is a good question. We haven't tried that because the LongNet internally avoids computing and storing the whole attention matrix to reduce the IO and memory cost.
