### ISSUE TITLE
AttributeError: 'ClassificationHead' object has no attribute 'longnet'

### ISSUE THREAD

**Issue by Ycblue** [prov-gigapath/prov-gigapath#18]
Hi, 
ClassificationHead class in `classification_head.py`  tries to freeze the parameters of `self.longnet.named_parameters()`, which does not exist. Instead, it should be changed to `self.slide_encoder.named_parameters()`:

```
if freeze:
    print("Freezing Pretrained GigaPath model")
    for name, param in self.slide_encoder.named_parameters():
        param.requires_grad = False
    print("Done") 
```
Cheers

**Comment by HanwenXuTHU** [comment]
Thanks for the good catch! This has been fixed in the latest update!
