### ISSUE TITLE
Asserterror "assert flash attn_func is not None"

### ISSUE THREAD

**Issue by gyboo** [prov-gigapath/prov-gigapath#19]
Thank you for you wonderfur project!
When I was running load_slide_encoder.py, the problem happend "assert flash attn_func is not None".

I think this problem mainly occured by 11 column in flash_attention.py:
from flash_attn.flash_attn_interface import flash_attn_func as _flash_attn_func

Is flash_attn a public package?Could you please offer the flash_atten.py or a method to get it

**Comment by HanwenXuTHU** [comment]
Hi, it looks like you didn't install flash-attn successfully. Please run the following command: `pip install flash-attn --no-build-isolation`

**Comment by gyboo** [comment]
Thank you for your response, it's useful. Could you please tell me your flash-attn version.

**Comment by HanwenXuTHU** [comment]
My flash-attn version is 2.5.8

**Comment by PerrySkywalker** [comment]
> My flash-attn version is 2.5.8
I have another problem.  RuntimeError: FlashAttention only support fp16 and bf16 data type.

**Comment by HanwenXuTHU** [comment]
> > My flash-attn version is 2.5.8
> > I have another problem.  RuntimeError: FlashAttention only support fp16 and bf16 data type.

Looks like you didn't enable the fp16 or bf16 mode. Please consider adding this line: `with torch.cuda.amp.autocast(dtype=torch.float16):`

**Comment by PerrySkywalker** [comment]
> > > My flash-attn version is 2.5.8
> > > I have another problem.  RuntimeError: FlashAttention only support fp16 and bf16 data type.
> 
> Looks like you didn't enable the fp16 or bf16 mode. Please consider adding this line: `with torch.cuda.amp.autocast(dtype=torch.float16):`

Thanks a lot. Slide-level encoder's output dimension is (1,768), is this correct?

**Comment by HanwenXuTHU** [comment]
> > > > My flash-attn version is 2.5.8
> > > > I have another problem.  RuntimeError: FlashAttention only support fp16 and bf16 data type.
> > 
> > 
> > Looks like you didn't enable the fp16 or bf16 mode. Please consider adding this line: `with torch.cuda.amp.autocast(dtype=torch.float16):`
> 
> Thanks a lot. Slide-level encoder's output dimension is (1,768), is this correct?

Following the default setting, it's correct.

**Comment by HanwenXuTHU** [comment]
Close it for now. Let me know if you have further questions!

**Comment by nakayamataiyo** [comment]
"assert flash_attn_func is not None" was the AssertionError I got too. I also tried the above solution, "pip install flash-attn --no-build-isolation", but it does not work with "error: subprocess-exited-with-error".
I would appreciate it if you could tell me how to deal with this.
I will show you the specific Error code below:

error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output].
      Traceback (most recent call last):.
        File "<string>", line 2, in <module
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Tanioka\AppData\Local\Temp\pip-install-yn21jtr2\flash-attn_1fb59a14c41849a6bf2eb4e7b7ae21dc\setup.py", line 95, in < module>
          subprocess.run(["git", "submodule", "update", "--init", "csrc/cutlass"])
        File "C:\Users\Tanioka\anaconda3\envs\gigapath\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process: File "C:\Users\Tanioka\anaconda3\envs\gigapath\libsubprocess.py
        File "C:\Users\Tanioka\anaconda3\envs\gigapath\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\Tanioka\anaconda3\envs\gigapath\lib\subprocess.py", line 1436, in _execute_child
          hp, ht, pid, tid = _winapi.
      FileNotFoundError: [WinError 2] The specified file cannot be found.
      [end of output].

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.

Translated with DeepL.com (free version)

**Comment by usuyama** [comment]
Flash attention on Windows is probably still tricky. Please check their
official repo
https://github.com/Dao-AILab/flash-attention
