### ISSUE TITLE
About mutation burden prediction task

### ISSUE THREAD

**Issue by yihu-dev** [prov-gigapath/prov-gigapath#20]
Hi,

For mutation burden prediction task, what is the threshold to label 'High TMB' and 'Low TMB'?
There is a LUAD-5-gene_TCGA.csv file in the dataset_csv fold, but I can not find the TMB task data.
Could you provide more information for this task?

Thanks.

**Comment by HanwenXuTHU** [comment]
Hi, we did the TMB prediction on our Prov-Path dataset. For the threshold, we determine TMB as high when it equals or is greater than 10mut/Mb.

**Comment by yihu-dev** [comment]
Thank you!
