### ISSUE TITLE
layers to the classifier

### ISSUE THREAD

**Issue by ahmedemadedlin** [prov-gigapath/prov-gigapath#21]
hello, Thanks for your nice work 
I wanted to ask what are the layers from which I should embed to the classifier
if i'm using some samples of PANDA dataset

**Comment by HanwenXuTHU** [comment]
Hi, please check the `FEATLAYER` in this [script](https://github.com/prov-gigapath/prov-gigapath/blob/main/scripts/run_panda.sh). For PANDA, we use the last layer's output as the features to the classifier.

**Comment by ahmedemadedlin** [comment]
Thanks, a lot

**Comment by Ycblue** [comment]
@HanwenXuTHU how do you determine which layers do use? 
Somewhere in the docs it is suggested to use multiple feature layers, 5 and 11 for example. 
Is there a procedure to determine which layers are more useful for a certain task?

**Comment by HanwenXuTHU** [comment]
> @HanwenXuTHU how do you determine which layers do use? Somewhere in the docs it is suggested to use multiple feature layers, 5 and 11 for example. Is there a procedure to determine which layers are more useful for a certain task?

I determined this based on the dev set performance. The general idea behind tuning this hyperparameter is that for tasks that rely on local features, incorporating the early layers can sometimes be useful.

**Comment by Ycblue** [comment]
Have you done any ablation studies on it? I couldn't find anything in the paper. Would be super interesting!

**Comment by HanwenXuTHU** [comment]
@Ycblue We have not conducted specific ablation studies yet. Agree that it would be an important direction to study which layers contain effective features for certain histopathology tasks.

**Comment by HanwenXuTHU** [comment]
Feel free to re-open it if anyone has more questions.

**Comment by askerlee** [comment]
> > @HanwenXuTHU how do you determine which layers do use? Somewhere in the docs it is suggested to use multiple feature layers, 5 and 11 for example. Is there a procedure to determine which layers are more useful for a certain task?
> 
> Good question! I determined this based on the dev set performance. The general idea behind tuning this hyperparameter is that for tasks that rely on local features, incorporating the early layers can sometimes be useful.

So LongNet does feature fusion / smoothing / denoising etc. and makes the features more global aware, is my understanding correct?
