### ISSUE TITLE
WSI --> WSI embedding script.

### ISSUE THREAD

**Issue by ozkilim** [prov-gigapath/prov-gigapath#24]
Thank you so much for this amazing work. I think people would really like a simple script that just takes a raw WSI (.svs .... etc ) and generates the final WSI level embedding.

**Comment by HanwenXuTHU** [comment]
Hi, our full pipeline has been released, please check this [document](https://github.com/prov-gigapath/prov-gigapath/blob/main/gigapath/preprocessing/preprocessing.md).

**Comment by ozkilim** [comment]
Fantastic. Thank you!
