### ISSUE TITLE
Slide feature during demo

### ISSUE THREAD

**Issue by ethannhx** [prov-gigapath/prov-gigapath#25]
![9ebdd25ab33598e793d211e199173da](https://github.com/prov-gigapath/prov-gigapath/assets/90835679/97c02421-e331-45ab-bb53-cb3719efdd54)
Hi, thanks a lot for the sharing.
Here is the problem I encountered while running the demo for inference. It seems that only the key "layer_0_embed" has the corresponding value with shape (1,768) while the other 12 values are all "nan". Is this the situation that supposed to happen?

**Comment by HanwenXuTHU** [comment]
Hi, this is something unexpected. It should output real values for embeddings from each layer.

**Comment by ethannhx** [comment]
It turns out that the tile encoder output are also nan.
So I commented this line of code in pipeline.py under gigapath folder and everything works just fine.
`with torch.cuda.amp.autocast(dtype=torch.float16):`

**Comment by HanwenXuTHU** [comment]
Hmm interesting. Which GPU device are you using?

**Comment by ethannhx** [comment]
Sry for the late reply. I used gtx3090 with Driver Version: 515.57 and CUDA Version: 11.7.
