### ISSUE TITLE
Data Splitting List

### ISSUE THREAD

**Issue by jingweitan** [prov-gigapath/prov-gigapath#28]
Hi, may I have the list for 10-cross validation splitting for your LUAD 5-gene mutation dataset? If possible, may I have the splitting list for other tasks as well?
Thanks in advance!

**Comment by HanwenXuTHU** [comment]
Hi Jingwei, we're checking to see if it's possible to release these splits. Please stay tuned!

**Comment by jingweitan** [comment]
Thanks! Looking forward to hearing from you.
