### ISSUE TITLE
slide_encoder module not in gigapath ,  

### ISSUE THREAD

**Issue by VatsalPatel18** [prov-gigapath/prov-gigapath#3]
Really state of the art work, Excited to run giga path for a few downstream Histopathology analysis, would appriciate the help here.

Have downloaded and followed the steps correctly, all packges and steps completed , activated the environment, imported gigapath yet facing issue over here. 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 3
      1 import gigapath
----> 3 slide_encoder = gigapath.slide_encoder.create_model("hf_hub:prov-gigapath/prov-gigapath", "gigapath_slide_enc12l768d", 1536)

AttributeError: module 'gigapath' has no attribute 'slide_encoder'

**Comment by VatsalPatel18** [comment]
gigapath is being loaded nevertheless not able to pull the slide_encoder,  

"(gigapath) [gp7@nibmg-gpu prov-gigapath]$ python3
Python 3.9.19 (main, May  6 2024, 19:43:03) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gigapath
>>> slide_encoder = gigapath.slide_encoder.create_model("hf_hub:prov-gigapath/prov-gigapath", "gigapath_slide_enc12l768d", 1536)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gigapath' has no attribute 'slide_encoder'
>>> "

**Comment by HanwenXuTHU** [comment]
Hi Vatsal, glad to see that you're running the model. Can you try following:
```
import gigapath.slide_encoder as slide_encoder
# load from HuggingFace
model = slide_encoder.create_model("hf_hub:prov-gigapath/prov-gigapath", "gigapath_slide_enc12l768d", 1536)
```
We will fix the code in README as well. This is a good catch!

**Comment by VatsalPatel18** [comment]
It works! Ciao
