### ISSUE TITLE
problem loading tile encoder

### ISSUE THREAD

**Issue by clyy21** [prov-gigapath/prov-gigapath#30]
Hi, thanks for the amazing work! I am new to machine learning. I've successfully loaded the slide encoder, but i am not sure how to load the tile encoder. I can only load from local because i can't connect to the huggingface. Is it possible to load the tile encoder from local?Really appreciate it if anyone could help :)

**Comment by HanwenXuTHU** [comment]
Hi thanks for reaching out. This function can be a reference for you [load_tile_slide_encoder(local_tile_encoder_path: str = "", local_slide_encoder_path: str = "")](https://github.com/prov-gigapath/prov-gigapath/blob/main/gigapath/pipeline.py). Setting the `local_tile_encoder_path` can enable loading from the local path.

**Comment by ethannhx** [comment]
You may try to load the model on your own computer or any other that can connect to huggingface, and save the model as .pth file. Then load the saved model directly using torch.load(). It works for me.
