### ISSUE TITLE
Possible position encoding bug for non-256px tiles

### ISSUE THREAD

**Issue by mielkec-gene** [prov-gigapath/prov-gigapath#32]
Brilliant work! I love this paper and Im impressed with the code quality.

I had a question about this line of code right here. Should the 256.0 in the denominator be changed if the tile size changes?

https://github.com/prov-gigapath/prov-gigapath/blob/9aca924b9d15f54ac62bd4e955851aba2d21da68/gigapath/slide_encoder.py#L176

I can see it both ways. At first I assumed that it should change, but then it occurred to me that perhaps it must remain fixed at 256 due to it being pre-trained at that tile size.

If it is a bug, happy to fix and send a pull request

**Comment by HanwenXuTHU** [comment]
Hi, thank you for your kind words! Good catch! `256.0` should be replaced by the `tile_size`. We will fix it in the next update!

**Comment by mielkec-gene** [comment]
Roger that - I've made a fork here but haven't yet tested it. Will do shortly!
https://github.com/mielkec-gene/prov-gigapath/commit/6c23da952b6eb7619ffff02101e6db0594fb709f
