### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by Polycoriander** [prov-gigapath/prov-gigapath#33]
Hello, are the tile encoder and slide encoder trained separately? Or are they trained together?

**Comment by HanwenXuTHU** [comment]
Hi, GigaPath has a two-stage training process, so the tile encoder and slide encoder are trained sequentially.

**Comment by Polycoriander** [comment]
Thanks！

**Comment by Polycoriander** [comment]
hi,when I download the model in huggingface, it shows "Your request to access this repo has been successfully submitted, and is pending a review from the repo's authors." How to deal with it? Can you help me?

> Hi, GigaPath has a two-stage training process, so the tile encoder and slide encoder are trained sequentially.

**Comment by HanwenXuTHU** [comment]
Hi, I just approved it. Can you check if you can access the model now?

**Comment by Polycoriander** [comment]
> Hi, I just approved it. Can you check if you can access the model now?

I can access the model.Thank you very much!

**Comment by HanwenXuTHU** [comment]
Great!
