### ISSUE TITLE
About semantic segmentation tasks

### ISSUE THREAD

**Issue by yuyu19970716** [prov-gigapath/prov-gigapath#34]
Hello, thank you very much for your excellent work, I would like to ask if it is possible to achieve semantic segmentation at the cell or tissue level in the code that is now being published? When will the code for the pretrained model be released?

**Comment by HanwenXuTHU** [comment]
Thank you for reaching out! We haven't explored the segmentation tasks. Agree this is an interesting direction to explore!

**Comment by FiReTiTi** [comment]
Any update about the segmentation?
I also would like to give it a try.
