### ISSUE TITLE
Tile coordinate (x, y) on WSI

### ISSUE THREAD

**Issue by shuangyanl** [prov-gigapath/prov-gigapath#35]
There are several places to use tile coordinates in the tile and slide encoder pipeline. Is the tile coordinate (x, y) the top left point or central point of a tile on a WSI that are expected in the pipeline?

**Comment by HanwenXuTHU** [comment]
Hi thanks for reaching out. We are currently working on releasing more details on the tiling process. It will probably come out by next week. Please stay tuned.

**Comment by alex-battikha** [comment]
Hi, do you have an update on the tiling process?

**Comment by HanwenXuTHU** [comment]
> Hi, do you have an update on the tiling process?

Thank you for the patience! We have now released the tiling scripts! Please check this [guide](https://github.com/prov-gigapath/prov-gigapath/blob/main/gigapath/preprocessing/preprocessing.md)!
