### ISSUE TITLE
The weight of the slide encoder of dimension 1024

### ISSUE THREAD

**Issue by sigsminx** [prov-gigapath/prov-gigapath#40]
Nice job!
Your code integrates Slide Encoder with an input dimension of 1024. The weight on Huggingface only involves only inputs with a dimension of 1536. I want to ask how to adjust the input with a dimension of 1024 or do you provide the corresponding weight?

**Comment by HanwenXuTHU** [comment]
Thanks for the kind word. Currently we only provide the slide encoder with 1536 input dimension, which is compatible with our provided tile encoder.
