### ISSUE TITLE
Tile encoder class location

### ISSUE THREAD

**Issue by lhallee** [prov-gigapath/prov-gigapath#5]
Hello!

Where is the PyTorch class for the tile encoder? I can't find the code in the repo. I'm curious because it would be great to be able to get (batch, num_patches, hidden_dim) output instead of just the CLS pooling. Will this be made available?
Best,
Logan

**Comment by HanwenXuTHU** [comment]
Hi, we're using a standard DINOv2 setting in timm. To obtain the patch level token embeddings, you can use the following:

```
with torch.no_grad():
    output = tile_encoder(sample_input)
    out_features = tile_encoder.forward_features(sample_input)
    print("Model output:", output.shape)
    print("Model features:", out_features.shape)
    print(out_features)
```
Here out_features has a shape of [batch_size, num_patch + 1, hidden_dim], where 1 corresponds to the CLS pooling.

**Comment by lhallee** [comment]
Thanks!!
