### ISSUE TITLE
looking forward for supplying DINO training code 

### ISSUE THREAD

**Issue by wu-bytecat** [prov-gigapath/prov-gigapath#60]
Hi thanks for sharing this amazing work and congratulations on the superb paper.
﻿
Would it be possible to share the pre training code? Specifically the DINO model and fine-tuning the DINO pretraining step further?
﻿
Thanks for viewing.

**Comment by HanwenXuTHU** [comment]
Hi thanks for reaching out! In our project, we didn't finetune the DINO encoder and only take embeddings from the pretrained model. We make use of the DINOv2 official codebase and follow the default settings. The main change is that we make a new data loader to read pathology tiles. So the official DINOv2 codebase could be a good starting point. I can offer some helps if you encounter problems when adapting their codebase.

**Comment by wu-bytecat** [comment]
> Hi thanks for reaching out! In our project, we didn't finetune the DINO encoder and only take embeddings from the pretrained model. We make use of the DINOv2 official codebase and follow the default settings. The main change is that we make a new data loader to read pathology tiles. So the official DINOv2 codebase could be a good starting point. I can offer some helps if you encounter problems when adapting their codebase.


Thank you for your generous response
May I ask how to store the output of tile enconder as an H5 file? I would greatly appreciate any response
Wishing you a good day
