### ISSUE TITLE
about data shuffle

### ISSUE THREAD

**Issue by Polycoriander** [prov-gigapath/prov-gigapath#66]
Hello, you're doing a great job. I have a question: why do we need to shuffle the dataset when fine-tuning? What's the difference between shuffling and not shuffling the data?

**Comment by HanwenXuTHU** [comment]
Hi, this shuffling can be seen as an augmentation approach, and I found it's useful to improve the performance on some downstream tasks.

**Comment by Polycoriander** [comment]
Does this imply that the order of the tiles is not important? In my understanding, LongNet's dilated attention calculates attention within local windows. If the tiles were completely shuffled, the tiles computed within the local window would be random. Would this have an impact? (I'm not entirely sure if my interpretation is correct, and I hope you can help clarify this.)

**Comment by Polycoriander** [comment]
> Hi, this shuffling can be seen as an augmentation approach, and I found it's useful to improve the performance on some downstream tasks.

Does this imply that the order of the tiles is not important? In my understanding, LongNet's dilated attention calculates attention within local windows. If the tiles were completely shuffled, the tiles computed within the local window would be random. Would this have an impact? (I'm not entirely sure if my interpretation is correct, and I hope you can help clarify this.)

**Comment by HanwenXuTHU** [comment]
Thank you, this is a good point! First, even if the order is shuffled, the coordinates are passed to the model so it can still be aware of the spatial locations. Second, in LongNet, it actually uses increasing window sizes, so the randomness decreases as the window size going up. For the largest window, which we set to the length of whole sequence, it always sees the same tiles. Actually, the tradition vision transformer is also invariant to the order of tokens. Designing the dilated attention patterns is indeed very interesting, we are hoping to explore more towards this direction!

**Comment by Polycoriander** [comment]
> Thank you, this is a good point! First, even if the order is shuffled, the coordinates are passed to the model so it can still be aware of the spatial locations. Second, in LongNet, it actually uses increasing window sizes, so the randomness decreases as the window size going up. For the largest window, which we set to the length of whole sequence, it always sees the same tiles. Actually, the tradition vision transformer is also invariant to the order of tokens. Designing the dilated attention patterns is indeed very interesting, we are hoping to explore more towards this direction!

I understand now, thank you for your explanation.
