### ISSUE TITLE
how to apply this model on my own data?

### ISSUE THREAD

**Issue by CharlotteChew** [prov-gigapath/prov-gigapath#71]
Hi, thanks for your incredible work for this.
I'm really a fresh master student to this field. First i followed your instructions of markdown. Then, i follow the 'demo', but i cant import 'gigapath' properly. I wander why and want to know if i have WSIs what is the proper way to apply this model.

**Comment by wu-bytecat** [comment]
Hello, I have encountered a similar issue before. If you are using VSCode, it may be due to a relative path import error. Adding the following code at the beginning of the file may solve your problem,
import sys
sys.path.append("..")

**Comment by CharlotteChew** [comment]
> Hello, I have encountered a similar issue before. If you are using VSCode, it may be due to a relative path import error. Adding the following code at the beginning of the file may solve your problem, import sys sys.path.append("..")

Hi, Thanks for your kind response. I am now using pycharm to apply this project, i am wandering if this error is caused because i am using a server. Cuz i followed your instructions, but it still caused error"ImportError: cannot import name 'EncoderConfig' from 'torchscale.architecture.config' (/opt/data/private/zwy/prov-gigapath/gigapath/torchscale/model/../../torchscale/architecture/config.py)" .I will be very grateful to receive your reply again.
