### ISSUE TITLE
Bug in pyproject.toml preventing installation as package

### ISSUE THREAD

**Issue by jamesdolezal** [prov-gigapath/prov-gigapath#80]
There is a bug in the `pyproject.toml` file which prevents installation of `gigapath` as a package. For example, running `pip install -e gigapath` will result in an error similar to the following upon package import:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.9/site-packages/gigapath/pipeline.py", line 10, in <module>
    import gigapath.slide_encoder as slide_encoder
  File ".../lib/python3.9/site-packages/gigapath/slide_encoder.py", line 29, in <module>
    from .torchscale.model.LongNet import make_longnet_from_name
ModuleNotFoundError: No module named 'gigapath.torchscale'
```

The issue is that the `torchscale` and `preprocessing` subdirectories are not being included in the package. The bug is in the pyproject.toml file, in which these lines:

```
[tool.setuptools.packages.find]
include = ["gigapath"]
```

should be:

```
[tool.setuptools.packages.find]
include = ["gigapath", "gigapath.*"]
```

This issue blocks the ability to install gigapath as a package via PIP:

```
gigapath @ git+ssh://git@github.com/prov-gigapath/prov-gigapath@main#egg=gigapath
```

I would fork this repository and apply the fix, but the license appears to disallow distribution.

**Comment by usuyama** [comment]
Thank you so much for reporting this! I’ve just pushed the proposed change.

**Comment by jamesdolezal** [comment]
Thank you!

**Comment by usuyama** [comment]
Thank you! Let me know if it works!

**Comment by jamesdolezal** [comment]
That fixed it! Thanks for the quick response.
